import type Phaser from "phaser";
import { TileType, type SpellKind, type PropType } from "shared";

// Every sprite this game loads, in one place, so preload() and every render
// call site agree on the same texture keys — see public/assets/ for the
// actual files (Kenney's CC0 "Isometric Blocks" and "Tiny Dungeon" packs).

// Each tile renders as the complete voxel cube (top face + its two baked-in
// south/east side faces) — for cliffs taller than one cube, extra full
// cubes stack underneath rather than a dedicated side-only crop (tried
// first; it had its own baked directional shading that repeating down a
// tall cliff turned into an ugly banded gradient — see
// WorldScene.createChunkLayer for the stacking math). An even earlier
// attempt used only a flat top-face crop tiled edge-to-edge, which looked
// wrong for a different reason: that crop's baked-in corner shading (meant
// for a single standalone cube icon) turned into an obvious repeating
// triangle pattern across open ground. Rendering the real 3D block is what
// actually fixes both.
export const TERRAIN_FULL_TEXTURE_KEYS: Record<number, string> = {
  [TileType.Grass]: "tile-grass-full",
  [TileType.Path]: "tile-path-full",
  [TileType.Water]: "tile-water-full",
  [TileType.Wall]: "tile-wall-full",
  // The rest of the Kenney "Isometric Blocks" voxel set — see TileType's
  // doc comment (shared/src/map.ts) for why these exist.
  [TileType.Sand]: "tile-sand-full",
  [TileType.Snow]: "tile-snow-full",
  [TileType.GreenBlock]: "tile-green-block-full",
  [TileType.OrangeTerracottaSolid]: "tile-orange-terracotta-solid-full",
  [TileType.Hedge]: "tile-hedge-full",
  [TileType.Ice]: "tile-ice-full",
  [TileType.CrackedIce]: "tile-cracked-ice-full",
  [TileType.MoltenRock]: "tile-molten-rock-full",
  [TileType.Stone]: "tile-stone-full",
  [TileType.GrassStoneSides]: "tile-grass-stone-sides-full",
  [TileType.DirtStoneSides]: "tile-dirt-stone-sides-full",
  [TileType.SandStoneSides]: "tile-sand-stone-sides-full",
  [TileType.SnowStoneSides]: "tile-snow-stone-sides-full",
  [TileType.WoodLog]: "tile-wood-log-full",
  [TileType.Marble]: "tile-marble-full",
  [TileType.JadeBlock]: "tile-jade-block-full",
  [TileType.RedBrick]: "tile-red-brick-full",
  [TileType.Sandstone]: "tile-sandstone-full",
  [TileType.WhiteMarbleSolid]: "tile-white-marble-solid-full",
  [TileType.TerracottaSmooth]: "tile-terracotta-smooth-full",
  [TileType.GreenWool]: "tile-green-wool-full",
  [TileType.BlueWool]: "tile-blue-wool-full",
  [TileType.CreamWool]: "tile-cream-wool-full",
  [TileType.WoodPlanks]: "tile-wood-planks-full",
  [TileType.BrickCoursed]: "tile-brick-coursed-full",
  [TileType.RockyDirt]: "tile-rocky-dirt-full",
  [TileType.SpeckledStone]: "tile-speckled-stone-full",
  [TileType.DarkStoneBrick]: "tile-dark-stone-brick-full",
  [TileType.CoalOre]: "tile-coal-ore-full",
  [TileType.EmeraldOre]: "tile-emerald-ore-full",
  [TileType.CopperOre]: "tile-copper-ore-full",
  [TileType.IronOre]: "tile-iron-ore-full",
  [TileType.GoldOre]: "tile-gold-ore-full",
  [TileType.DiamondOre]: "tile-diamond-ore-full",
  [TileType.RedClay]: "tile-red-clay-full",
  [TileType.RedClayMottled]: "tile-red-clay-mottled-full",
  [TileType.RedClayRough]: "tile-red-clay-rough-full",
  [TileType.RedClayEmerald]: "tile-red-clay-emerald-full",
  [TileType.RedClayEmeraldRich]: "tile-red-clay-emerald-rich-full",
  [TileType.BasaltCoal]: "tile-basalt-coal-full",
  [TileType.StoneEmeraldAlt]: "tile-stone-emerald-alt-full",
  [TileType.StoneCopperAlt]: "tile-stone-copper-alt-full",
  [TileType.StoneIronAlt]: "tile-stone-iron-alt-full",
  [TileType.StoneGoldRich]: "tile-stone-gold-rich-full",
  [TileType.StoneDiamondAlt]: "tile-stone-diamond-alt-full",
  [TileType.LightGrayStone]: "tile-light-gray-stone-full",
  [TileType.PaleStone]: "tile-pale-stone-full",
  [TileType.SlateStone]: "tile-slate-stone-full",
  [TileType.SlateRuby]: "tile-slate-ruby-full",
  [TileType.SlateRubyRich]: "tile-slate-ruby-rich-full",
  [TileType.DirtSolid]: "tile-dirt-solid-full",
  [TileType.GrassSolidBright]: "tile-grass-solid-bright-full",
  [TileType.GrassClassic]: "tile-grass-classic-full",
};

// Pixel dimensions baked into every -full terrain PNG (see
// public/assets/tiles/) — all four cropped from the same Kenney "Isometric
// Blocks" voxel cube layout, so one set of measurements covers all of them.
// The cube image is the top diamond plus its two baked-in side faces
// stacked below it. TOP_HEIGHT isn't the idealized "exactly half of WIDTH"
// a mathematically perfect 2:1 diamond would have (111/2 = 55.5) — measured
// directly from the actual artwork's alpha channel (every one of these four
// PNGs' top face is fully opaque edge-to-edge, x=0..110, at row 31, i.e.
// TOP_HEIGHT/2), the art's top face reads as visually taller than that.
// Using the idealized value here throws off WorldScene.createChunkLayer's
// topOriginYFraction (which positions every cube off this) by a few
// pixels, consistently, on every single tile — the measured value is what
// actually lines a cube's top-face center up with its tile's true grid
// center.
export const TERRAIN_CUBE_SOURCE_WIDTH = 111;
export const TERRAIN_CUBE_SOURCE_HEIGHT = 128;
export const TERRAIN_CUBE_SOURCE_TOP_HEIGHT = 62;

const TERRAIN_ASSET_PATHS: Record<string, string> = {
  "tile-grass-full": "/assets/tiles/grass-full.png",
  "tile-path-full": "/assets/tiles/path-full.png",
  "tile-water-full": "/assets/tiles/water-full.png",
  "tile-wall-full": "/assets/tiles/wall-full.png",
  "tile-sand-full": "/assets/tiles/sand-full.png",
  "tile-snow-full": "/assets/tiles/snow-full.png",
  "tile-green-block-full": "/assets/tiles/green-block-full.png",
  "tile-orange-terracotta-solid-full": "/assets/tiles/orange-terracotta-solid-full.png",
  "tile-hedge-full": "/assets/tiles/hedge-full.png",
  "tile-ice-full": "/assets/tiles/ice-full.png",
  "tile-cracked-ice-full": "/assets/tiles/cracked-ice-full.png",
  "tile-molten-rock-full": "/assets/tiles/molten-rock-full.png",
  "tile-stone-full": "/assets/tiles/stone-full.png",
  "tile-grass-stone-sides-full": "/assets/tiles/grass-stone-sides-full.png",
  "tile-dirt-stone-sides-full": "/assets/tiles/dirt-stone-sides-full.png",
  "tile-sand-stone-sides-full": "/assets/tiles/sand-stone-sides-full.png",
  "tile-snow-stone-sides-full": "/assets/tiles/snow-stone-sides-full.png",
  "tile-wood-log-full": "/assets/tiles/wood-log-full.png",
  "tile-marble-full": "/assets/tiles/marble-full.png",
  "tile-jade-block-full": "/assets/tiles/jade-block-full.png",
  "tile-red-brick-full": "/assets/tiles/red-brick-full.png",
  "tile-sandstone-full": "/assets/tiles/sandstone-full.png",
  "tile-white-marble-solid-full": "/assets/tiles/white-marble-solid-full.png",
  "tile-terracotta-smooth-full": "/assets/tiles/terracotta-smooth-full.png",
  "tile-green-wool-full": "/assets/tiles/green-wool-full.png",
  "tile-blue-wool-full": "/assets/tiles/blue-wool-full.png",
  "tile-cream-wool-full": "/assets/tiles/cream-wool-full.png",
  "tile-wood-planks-full": "/assets/tiles/wood-planks-full.png",
  "tile-brick-coursed-full": "/assets/tiles/brick-coursed-full.png",
  "tile-rocky-dirt-full": "/assets/tiles/rocky-dirt-full.png",
  "tile-speckled-stone-full": "/assets/tiles/speckled-stone-full.png",
  "tile-dark-stone-brick-full": "/assets/tiles/dark-stone-brick-full.png",
  "tile-coal-ore-full": "/assets/tiles/coal-ore-full.png",
  "tile-emerald-ore-full": "/assets/tiles/emerald-ore-full.png",
  "tile-copper-ore-full": "/assets/tiles/copper-ore-full.png",
  "tile-iron-ore-full": "/assets/tiles/iron-ore-full.png",
  "tile-gold-ore-full": "/assets/tiles/gold-ore-full.png",
  "tile-diamond-ore-full": "/assets/tiles/diamond-ore-full.png",
  "tile-red-clay-full": "/assets/tiles/red-clay-full.png",
  "tile-red-clay-mottled-full": "/assets/tiles/red-clay-mottled-full.png",
  "tile-red-clay-rough-full": "/assets/tiles/red-clay-rough-full.png",
  "tile-red-clay-emerald-full": "/assets/tiles/red-clay-emerald-full.png",
  "tile-red-clay-emerald-rich-full": "/assets/tiles/red-clay-emerald-rich-full.png",
  "tile-basalt-coal-full": "/assets/tiles/basalt-coal-full.png",
  "tile-stone-emerald-alt-full": "/assets/tiles/stone-emerald-alt-full.png",
  "tile-stone-copper-alt-full": "/assets/tiles/stone-copper-alt-full.png",
  "tile-stone-iron-alt-full": "/assets/tiles/stone-iron-alt-full.png",
  "tile-stone-gold-rich-full": "/assets/tiles/stone-gold-rich-full.png",
  "tile-stone-diamond-alt-full": "/assets/tiles/stone-diamond-alt-full.png",
  "tile-light-gray-stone-full": "/assets/tiles/light-gray-stone-full.png",
  "tile-pale-stone-full": "/assets/tiles/pale-stone-full.png",
  "tile-slate-stone-full": "/assets/tiles/slate-stone-full.png",
  "tile-slate-ruby-full": "/assets/tiles/slate-ruby-full.png",
  "tile-slate-ruby-rich-full": "/assets/tiles/slate-ruby-rich-full.png",
  "tile-dirt-solid-full": "/assets/tiles/dirt-solid-full.png",
  "tile-grass-solid-bright-full": "/assets/tiles/grass-solid-bright-full.png",
  "tile-grass-classic-full": "/assets/tiles/grass-classic-full.png",
};

// Decorative furniture/dungeon-dressing props an admin can paint onto a tile
// (see shared/src/api-types.ts's PropType and MapTile.propType) — purely
// visual, drawn on top of the tile it's painted on with no gameplay effect
// of its own (an admin who also wants it to block movement pairs it with
// the existing Barrier tool on the same cell).
export const PROP_TEXTURE_KEYS: Record<PropType, string> = {
  table: "prop-table",
  chest: "prop-chest",
  dresser: "prop-dresser",
  barrel: "prop-barrel",
  torch: "prop-torch",
  door: "prop-door",
  fence: "prop-fence",
  gravestone: "prop-gravestone",
  furnace: "prop-furnace",
  crate: "prop-crate",
  dirtFloor: "prop-dirt-floor",
  dirtFloorVar2: "prop-dirt-floor-var2",
  dirtFloorVar3: "prop-dirt-floor-var3",
  dirtFloorVar4: "prop-dirt-floor-var4",
  stoneArchwayTopLeft: "prop-stone-archway-top-left",
  stoneArchwayTopRight: "prop-stone-archway-top-right",
  stonePillarTop: "prop-stone-pillar-top",
  ironSconce: "prop-iron-sconce",
  torchSconceGreen: "prop-torch-sconce-green",
  greenGemTorch: "prop-green-gem-torch",
  darkFloor: "prop-dark-floor",
  darkFloorVar2: "prop-dark-floor-var2",
  dirtFloorPebbles: "prop-dirt-floor-pebbles",
  dirtFloorPebbles2: "prop-dirt-floor-pebbles2",
  stoneArchwayOpenLeft: "prop-stone-archway-open-left",
  stoneArchwayOpenRight: "prop-stone-archway-open-right",
  stonePillarBase: "prop-stone-pillar-base",
  stonePillarCap: "prop-stone-pillar-cap",
  wallSconce: "prop-wall-sconce",
  gargoyleFaceLeft: "prop-gargoyle-face-left",
  gargoyleFaceRight: "prop-gargoyle-face-right",
  darkWall: "prop-dark-wall",
  darkWallVar2: "prop-dark-wall-var2",
  darkWallVar3: "prop-dark-wall-var3",
  dirtFloorRocks: "prop-dirt-floor-rocks",
  dirtFloorRocks2: "prop-dirt-floor-rocks2",
  stoneFrameLeft: "prop-stone-frame-left",
  stoneFrameRight: "prop-stone-frame-right",
  stoneWall: "prop-stone-wall",
  redBanner: "prop-red-banner",
  sandFloor: "prop-sand-floor",
  stoneVent: "prop-stone-vent",
  emeraldAltar: "prop-emerald-altar",
  woodDoorClosedLeft: "prop-wood-door-closed-left",
  woodDoorClosedMid: "prop-wood-door-closed-mid",
  woodDoorClosedRight: "prop-wood-door-closed-right",
  plankWall: "prop-plank-wall",
  plankWallVar2: "prop-plank-wall-var2",
  plankWallVar3: "prop-plank-wall-var3",
  plankWallEdge: "prop-plank-wall-edge",
  stoneWallVar2: "prop-stone-wall-var2",
  crossWindow: "prop-cross-window",
  stoneFloorTiles: "prop-stone-floor-tiles",
  stoneSarcophagus: "prop-stone-sarcophagus",
  emeraldSarcophagus: "prop-emerald-sarcophagus",
  woodDoorKnobLeft: "prop-wood-door-knob-left",
  woodDoorKnobMid: "prop-wood-door-knob-mid",
  woodDoorKnobRight: "prop-wood-door-knob-right",
  sandFloorVar2: "prop-sand-floor-var2",
  sandFloorSpeckled: "prop-sand-floor-speckled",
  sandFloorVar3: "prop-sand-floor-var3",
  sandFloorSpeckled2: "prop-sand-floor-speckled2",
  sandFloorVar4: "prop-sand-floor-var4",
  sandFloorVar5: "prop-sand-floor-var5",
  metalLocker: "prop-metal-locker",
  metalLockerVar2: "prop-metal-locker-var2",
  shieldEmblem: "prop-shield-emblem",
  stoneBrickWall: "prop-stone-brick-wall",
  stoneBrickWallVar2: "prop-stone-brick-wall-var2",
  stoneBrickWallVar3: "prop-stone-brick-wall-var3",
  targetMarker: "prop-target-marker",
  bandageIcon: "prop-bandage-icon",
  clothIcon: "prop-cloth-icon",
  woodDresser: "prop-wood-dresser",
  anvil: "prop-anvil",
  metalCabinet: "prop-metal-cabinet",
  roundShield: "prop-round-shield",
  ironGate: "prop-iron-gate",
  ironGateVar2: "prop-iron-gate-var2",
  spiralRailing: "prop-spiral-railing",
  labyrinthFloorPart1: "prop-labyrinth-floor-part1",
  labyrinthFloorPart2: "prop-labyrinth-floor-part2",
  woodTable: "prop-wood-table",
  woodStool: "prop-wood-stool",
  golemHead: "prop-golem-head",
  woodDresserVar2: "prop-wood-dresser-var2",
  woodFence: "prop-wood-fence",
  woodFenceVar2: "prop-wood-fence-var2",
  woodFenceVar3: "prop-wood-fence-var3",
  woodFenceVar4: "prop-wood-fence-var4",
  labyrinthFloorPart3: "prop-labyrinth-floor-part3",
  labyrinthFloorPart4: "prop-labyrinth-floor-part4",
  labyrinthCenter: "prop-labyrinth-center",
  labyrinthFloorPart5: "prop-labyrinth-floor-part5",
  portraitPurpleWizard: "prop-portrait-purple-wizard",
  portraitVillager: "prop-portrait-villager",
  portraitVillagerVar2: "prop-portrait-villager-var2",
  portraitDwarf: "prop-portrait-dwarf",
  portraitVillagerVar3: "prop-portrait-villager-var3",
  chestClosed: "prop-chest-closed",
  chestOpen: "prop-chest-open",
  mimicChest: "prop-mimic-chest",
  mimicChestOpenMouth: "prop-mimic-chest-open-mouth",
  labyrinthFloorPart6: "prop-labyrinth-floor-part6",
  labyrinthFloorPart7: "prop-labyrinth-floor-part7",
  labyrinthFloorPart8: "prop-labyrinth-floor-part8",
  portraitKnight: "prop-portrait-knight",
  portraitKnightVar2: "prop-portrait-knight-var2",
  portraitVillagerVar4: "prop-portrait-villager-var4",
  portraitGirl: "prop-portrait-girl",
  portraitDwarfVar2: "prop-portrait-dwarf-var2",
  frameIcon: "prop-frame-icon",
  blueGem: "prop-blue-gem",
  dagger: "prop-dagger",
  sword: "prop-sword",
  swordOrnate: "prop-sword-ornate",
  swordSilver: "prop-sword-silver",
  swordRuby: "prop-sword-ruby",
  slimeMonster: "prop-slime-monster",
  ogreMonster: "prop-ogre-monster",
  crabMonster: "prop-crab-monster",
  portraitOldMan: "prop-portrait-old-man",
  portraitGreenDwarf: "prop-portrait-green-dwarf",
  potionGray: "prop-potion-gray",
  potionGreen: "prop-potion-green",
  potionRed: "prop-potion-red",
  potionBlue: "prop-potion-blue",
  hammer: "prop-hammer",
  mace: "prop-mace",
  flail: "prop-flail",
  beastFace: "prop-beast-face",
  ghost: "prop-ghost",
  monsterShield: "prop-monster-shield",
  helmet: "prop-helmet",
  helmetVar2: "prop-helmet-var2",
  staffGreen: "prop-staff-green",
  staffRed: "prop-staff-red",
  staffBlueTip: "prop-staff-blue-tip",
  staffBlue: "prop-staff-blue",
  wandPurple: "prop-wand-purple",
  wandBlue: "prop-wand-blue",
  swordBasic: "prop-sword-basic",
};

const PROP_ASSET_PATHS: Record<string, string> = {
  "prop-table": "/assets/props/table.png",
  "prop-chest": "/assets/props/chest.png",
  "prop-dresser": "/assets/props/dresser.png",
  "prop-barrel": "/assets/props/barrel.png",
  "prop-torch": "/assets/props/torch.png",
  "prop-door": "/assets/props/door.png",
  "prop-fence": "/assets/props/fence.png",
  "prop-gravestone": "/assets/props/gravestone.png",
  "prop-furnace": "/assets/props/furnace.png",
  "prop-crate": "/assets/props/crate.png",
  "prop-dirt-floor": "/assets/props/dirt-floor.png",
  "prop-dirt-floor-var2": "/assets/props/dirt-floor-var2.png",
  "prop-dirt-floor-var3": "/assets/props/dirt-floor-var3.png",
  "prop-dirt-floor-var4": "/assets/props/dirt-floor-var4.png",
  "prop-stone-archway-top-left": "/assets/props/stone-archway-top-left.png",
  "prop-stone-archway-top-right": "/assets/props/stone-archway-top-right.png",
  "prop-stone-pillar-top": "/assets/props/stone-pillar-top.png",
  "prop-iron-sconce": "/assets/props/iron-sconce.png",
  "prop-torch-sconce-green": "/assets/props/torch-sconce-green.png",
  "prop-green-gem-torch": "/assets/props/green-gem-torch.png",
  "prop-dark-floor": "/assets/props/dark-floor.png",
  "prop-dark-floor-var2": "/assets/props/dark-floor-var2.png",
  "prop-dirt-floor-pebbles": "/assets/props/dirt-floor-pebbles.png",
  "prop-dirt-floor-pebbles2": "/assets/props/dirt-floor-pebbles2.png",
  "prop-stone-archway-open-left": "/assets/props/stone-archway-open-left.png",
  "prop-stone-archway-open-right": "/assets/props/stone-archway-open-right.png",
  "prop-stone-pillar-base": "/assets/props/stone-pillar-base.png",
  "prop-stone-pillar-cap": "/assets/props/stone-pillar-cap.png",
  "prop-wall-sconce": "/assets/props/wall-sconce.png",
  "prop-gargoyle-face-left": "/assets/props/gargoyle-face-left.png",
  "prop-gargoyle-face-right": "/assets/props/gargoyle-face-right.png",
  "prop-dark-wall": "/assets/props/dark-wall.png",
  "prop-dark-wall-var2": "/assets/props/dark-wall-var2.png",
  "prop-dark-wall-var3": "/assets/props/dark-wall-var3.png",
  "prop-dirt-floor-rocks": "/assets/props/dirt-floor-rocks.png",
  "prop-dirt-floor-rocks2": "/assets/props/dirt-floor-rocks2.png",
  "prop-stone-frame-left": "/assets/props/stone-frame-left.png",
  "prop-stone-frame-right": "/assets/props/stone-frame-right.png",
  "prop-stone-wall": "/assets/props/stone-wall.png",
  "prop-red-banner": "/assets/props/red-banner.png",
  "prop-sand-floor": "/assets/props/sand-floor.png",
  "prop-stone-vent": "/assets/props/stone-vent.png",
  "prop-emerald-altar": "/assets/props/emerald-altar.png",
  "prop-wood-door-closed-left": "/assets/props/wood-door-closed-left.png",
  "prop-wood-door-closed-mid": "/assets/props/wood-door-closed-mid.png",
  "prop-wood-door-closed-right": "/assets/props/wood-door-closed-right.png",
  "prop-plank-wall": "/assets/props/plank-wall.png",
  "prop-plank-wall-var2": "/assets/props/plank-wall-var2.png",
  "prop-plank-wall-var3": "/assets/props/plank-wall-var3.png",
  "prop-plank-wall-edge": "/assets/props/plank-wall-edge.png",
  "prop-stone-wall-var2": "/assets/props/stone-wall-var2.png",
  "prop-cross-window": "/assets/props/cross-window.png",
  "prop-stone-floor-tiles": "/assets/props/stone-floor-tiles.png",
  "prop-stone-sarcophagus": "/assets/props/stone-sarcophagus.png",
  "prop-emerald-sarcophagus": "/assets/props/emerald-sarcophagus.png",
  "prop-wood-door-knob-left": "/assets/props/wood-door-knob-left.png",
  "prop-wood-door-knob-mid": "/assets/props/wood-door-knob-mid.png",
  "prop-wood-door-knob-right": "/assets/props/wood-door-knob-right.png",
  "prop-sand-floor-var2": "/assets/props/sand-floor-var2.png",
  "prop-sand-floor-speckled": "/assets/props/sand-floor-speckled.png",
  "prop-sand-floor-var3": "/assets/props/sand-floor-var3.png",
  "prop-sand-floor-speckled2": "/assets/props/sand-floor-speckled2.png",
  "prop-sand-floor-var4": "/assets/props/sand-floor-var4.png",
  "prop-sand-floor-var5": "/assets/props/sand-floor-var5.png",
  "prop-metal-locker": "/assets/props/metal-locker.png",
  "prop-metal-locker-var2": "/assets/props/metal-locker-var2.png",
  "prop-shield-emblem": "/assets/props/shield-emblem.png",
  "prop-stone-brick-wall": "/assets/props/stone-brick-wall.png",
  "prop-stone-brick-wall-var2": "/assets/props/stone-brick-wall-var2.png",
  "prop-stone-brick-wall-var3": "/assets/props/stone-brick-wall-var3.png",
  "prop-target-marker": "/assets/props/target-marker.png",
  "prop-bandage-icon": "/assets/props/bandage-icon.png",
  "prop-cloth-icon": "/assets/props/cloth-icon.png",
  "prop-wood-dresser": "/assets/props/wood-dresser.png",
  "prop-anvil": "/assets/props/anvil.png",
  "prop-metal-cabinet": "/assets/props/metal-cabinet.png",
  "prop-round-shield": "/assets/props/round-shield.png",
  "prop-iron-gate": "/assets/props/iron-gate.png",
  "prop-iron-gate-var2": "/assets/props/iron-gate-var2.png",
  "prop-spiral-railing": "/assets/props/spiral-railing.png",
  "prop-labyrinth-floor-part1": "/assets/props/labyrinth-floor-part1.png",
  "prop-labyrinth-floor-part2": "/assets/props/labyrinth-floor-part2.png",
  "prop-wood-table": "/assets/props/wood-table.png",
  "prop-wood-stool": "/assets/props/wood-stool.png",
  "prop-golem-head": "/assets/props/golem-head.png",
  "prop-wood-dresser-var2": "/assets/props/wood-dresser-var2.png",
  "prop-wood-fence": "/assets/props/wood-fence.png",
  "prop-wood-fence-var2": "/assets/props/wood-fence-var2.png",
  "prop-wood-fence-var3": "/assets/props/wood-fence-var3.png",
  "prop-wood-fence-var4": "/assets/props/wood-fence-var4.png",
  "prop-labyrinth-floor-part3": "/assets/props/labyrinth-floor-part3.png",
  "prop-labyrinth-floor-part4": "/assets/props/labyrinth-floor-part4.png",
  "prop-labyrinth-center": "/assets/props/labyrinth-center.png",
  "prop-labyrinth-floor-part5": "/assets/props/labyrinth-floor-part5.png",
  "prop-portrait-purple-wizard": "/assets/props/portrait-purple-wizard.png",
  "prop-portrait-villager": "/assets/props/portrait-villager.png",
  "prop-portrait-villager-var2": "/assets/props/portrait-villager-var2.png",
  "prop-portrait-dwarf": "/assets/props/portrait-dwarf.png",
  "prop-portrait-villager-var3": "/assets/props/portrait-villager-var3.png",
  "prop-chest-closed": "/assets/props/chest-closed.png",
  "prop-chest-open": "/assets/props/chest-open.png",
  "prop-mimic-chest": "/assets/props/mimic-chest.png",
  "prop-mimic-chest-open-mouth": "/assets/props/mimic-chest-open-mouth.png",
  "prop-labyrinth-floor-part6": "/assets/props/labyrinth-floor-part6.png",
  "prop-labyrinth-floor-part7": "/assets/props/labyrinth-floor-part7.png",
  "prop-labyrinth-floor-part8": "/assets/props/labyrinth-floor-part8.png",
  "prop-portrait-knight": "/assets/props/portrait-knight.png",
  "prop-portrait-knight-var2": "/assets/props/portrait-knight-var2.png",
  "prop-portrait-villager-var4": "/assets/props/portrait-villager-var4.png",
  "prop-portrait-girl": "/assets/props/portrait-girl.png",
  "prop-portrait-dwarf-var2": "/assets/props/portrait-dwarf-var2.png",
  "prop-frame-icon": "/assets/props/frame-icon.png",
  "prop-blue-gem": "/assets/props/blue-gem.png",
  "prop-dagger": "/assets/props/dagger.png",
  "prop-sword": "/assets/props/sword.png",
  "prop-sword-ornate": "/assets/props/sword-ornate.png",
  "prop-sword-silver": "/assets/props/sword-silver.png",
  "prop-sword-ruby": "/assets/props/sword-ruby.png",
  "prop-slime-monster": "/assets/props/slime-monster.png",
  "prop-ogre-monster": "/assets/props/ogre-monster.png",
  "prop-crab-monster": "/assets/props/crab-monster.png",
  "prop-portrait-old-man": "/assets/props/portrait-old-man.png",
  "prop-portrait-green-dwarf": "/assets/props/portrait-green-dwarf.png",
  "prop-potion-gray": "/assets/props/potion-gray.png",
  "prop-potion-green": "/assets/props/potion-green.png",
  "prop-potion-red": "/assets/props/potion-red.png",
  "prop-potion-blue": "/assets/props/potion-blue.png",
  "prop-hammer": "/assets/props/hammer.png",
  "prop-mace": "/assets/props/mace.png",
  "prop-flail": "/assets/props/flail.png",
  "prop-beast-face": "/assets/props/beast-face.png",
  "prop-ghost": "/assets/props/ghost.png",
  "prop-monster-shield": "/assets/props/monster-shield.png",
  "prop-helmet": "/assets/props/helmet.png",
  "prop-helmet-var2": "/assets/props/helmet-var2.png",
  "prop-staff-green": "/assets/props/staff-green.png",
  "prop-staff-red": "/assets/props/staff-red.png",
  "prop-staff-blue-tip": "/assets/props/staff-blue-tip.png",
  "prop-staff-blue": "/assets/props/staff-blue.png",
  "prop-wand-purple": "/assets/props/wand-purple.png",
  "prop-wand-blue": "/assets/props/wand-blue.png",
  "prop-sword-basic": "/assets/props/sword-basic.png",
};

// Keyed by ClassTemplate/MonsterTemplate/NpcTemplate *name* (not id) — those
// names are admin-authored content, not a fixed enum, so an unmapped name
// (a class/monster/NPC created after this list was written) falls back to
// a same-category default below rather than throwing.
export const CLASS_TEXTURE_KEYS: Record<string, string> = {
  Warrior: "char-warrior",
  Rogue: "char-rogue",
  Mage: "char-mage",
  Priest: "char-priest",
};

export const MONSTER_TEXTURE_KEYS: Record<string, string> = {
  Slime: "char-slime",
};

export const NPC_TEXTURE_KEYS: Record<string, string> = {
  Guide: "char-guide",
  Sage: "char-sage",
};

// One fallback per category (rather than one shared default) so an
// admin-added monster/NPC that isn't in the maps above still reads as
// "a monster" / "an NPC" instead of literally rendering as a Warrior.
export const DEFAULT_CLASS_TEXTURE_KEY = "char-warrior";
export const DEFAULT_MONSTER_TEXTURE_KEY = "char-slime";
export const DEFAULT_NPC_TEXTURE_KEY = "char-guide";

const CHARACTER_ASSET_PATHS: Record<string, string> = {
  "char-warrior": "/assets/characters/warrior.png",
  "char-rogue": "/assets/characters/rogue.png",
  "char-mage": "/assets/characters/mage.png",
  "char-priest": "/assets/characters/priest.png",
  "char-slime": "/assets/characters/slime.png",
  "char-guide": "/assets/characters/guide.png",
  "char-sage": "/assets/characters/sage.png",
};

// One icon per spell *kind* (not per spell) — a class's individual spells
// are admin-authored (name/color/etc.), but they're built from this fixed
// set of kinds (see shared/src/spells.ts), so an icon per kind covers every
// spell any class can ever have without needing per-spell icon authoring.
export const SPELL_KIND_ICON_KEYS: Record<SpellKind, string> = {
  single: "icon-single",
  aoe: "icon-aoe",
  groundAoe: "icon-groundAoe",
  slow: "icon-slow",
  heal: "icon-heal",
  interrupt: "icon-interrupt",
};

const ICON_ASSET_PATHS: Record<string, string> = {
  "icon-single": "/assets/icons/icon-single.png",
  "icon-aoe": "/assets/icons/icon-aoe.png",
  "icon-groundAoe": "/assets/icons/icon-groundAoe.png",
  "icon-slow": "/assets/icons/icon-slow.png",
  "icon-heal": "/assets/icons/icon-heal.png",
  "icon-interrupt": "/assets/icons/icon-interrupt.png",
};

export function preloadGameAssets(scene: Phaser.Scene) {
  for (const [key, path] of Object.entries(TERRAIN_ASSET_PATHS)) scene.load.image(key, path);
  for (const [key, path] of Object.entries(PROP_ASSET_PATHS)) scene.load.image(key, path);
  for (const [key, path] of Object.entries(CHARACTER_ASSET_PATHS)) scene.load.image(key, path);
  for (const [key, path] of Object.entries(ICON_ASSET_PATHS)) scene.load.image(key, path);
}
